---
title: "Importing data"
author: "Jeffrey R. Stevens"
date: "2025-02-07"
output: html_document
execute:
  freeze: auto
---


1. Download <https://jeffreyrstevens.github.io/dpavir2025/data/newdata.csv> and save it in your `data/` directory.

1. Import `newdata.csv` into an object called `newdata` using `read.csv()`.
```{r}
newdata <- read.csv(here::here("data/newdata.csv"))
```

3. Import <https://jeffreyrstevens.github.io/dpavir2025/data/newdata2.csv> directly from the URL using `readr::read_csv()`.
```{r}
library(readr)
newdata2 <- read_csv("https://jeffreyrstevens.github.io/dpavir2025/data/newdata2.csv")
```

4. Repeat the previous import of `newdata2.csv`, but add the arguments `col_select = c("Breed", "links")` and `show_col_types = FALSE` and name the object `newdata3`.
```{r}
newdata3 <- read_csv("https://jeffreyrstevens.github.io/dpavir2025/data/newdata2.csv", col_select = c("Breed", "links"), show_col_types = FALSE)
```

5. Export the `newdata3` data as a CSV file to your `data/` directory.
```{r}
write_csv(newdata3, here::here("data/newdata3.csv"))
```

