---
title: 'Workflows'
author:
  - Jeff Stevens
date: '2025-01-29'
categories: 
  - "module 1"
  - "week 2"
  - "file systems"
  - paths
  - "RStudio Projects"
  - "working directories"
description: "Access file systems with paths and set working directories with RStudio Projects"
execute:
  freeze: auto
draft: false
---

Using R involves working with multiple files in your project folders. To read in data and save figures, you need to be able to navigate the directory structure of your file system. 

## Learning objectives

* Access files in directories with file managers and terminals
* Distinguish between absolute and relative directory paths
* Navigate across subdirectories in a terminal
* Set working directories with RStudio Projects

## Pre-meeting

To prepare for this class meeting, please do the following:

* Read [R4DS2 6](https://r4ds.hadley.nz/workflow-scripts.html){target='_blank'}

## Class meeting

* Directory structure
* Paths
* Working directories
* RStudio Projects
* Running commands
* [Slides](../../slides/04_workflows.qmd){target="_blank"}

## Homework after the class meeting
### Wrap up this lesson

* Complete the [exercises](https://its-ianr-shiny.unl.edu/users/jstevens5/dpavir2025/04_workflows/){target='_blank'}

### For next class meeting

* Read [R Markdown](https://rmarkdown.rstudio.com/articles_intro.html), complete [Markdown tutorial](https://commonmark.org/help/tutorial/){target='_blank'}
