{
  "hash": "e8dda99c506319a5e75a3e535b09d34d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Publications\"\nauthor: \"Jeff Stevens\"\ndate: \"2023-05-05\"\ndate-format: iso\nexecute:\n  echo: true\n  freeze: auto\nformat:\n  revealjs: \n    theme: custom.scss\n    slide-number: true\n    code-line-numbers: false\n    highlight-style: github\n    code-overflow: wrap\n    footer: \"[DPaViR 2025](https://jeffreyrstevens.github.io/dpavir2025)\"\n    code-link: true\n    logo: \"../logo/dpavir_hex.png\"\n---\n\n\n\n\n\n\n\n# Journal article templates\n\n\n## Templates\n\n[{rticles}](https://pkgs.rstudio.com/rticles/)\n\n![](../images/rticles_hex.png){.absolute width=\"15%\" top=\"-5%\" left=\"85%\"}\n\n![](../images/rticles-templates.png){fig-align=\"center\" width=\"55%\"}\n\n\n## APA template\n\n[{papaja}](http://frederikaust.com/papaja_man/)\n\n![](../images/papaja_hex.png){.absolute width=\"15%\" top=\"-5%\" left=\"85%\"}\n\n![](../images/papaja-template.png){fig-align=\"center\" width=\"55%\"}\n\n\n## APA template\n\n[{papaja}](http://frederikaust.com/papaja_man/)\n\n![](../images/papaja_hex.png){.absolute width=\"15%\" top=\"-5%\" left=\"85%\"}\n\n* YAML header\n\n* `r_refs()` and `cite_r()`\n\n* [APA 7](https://github.com/crsh/papaja/issues/342)\n\n\n## Quarto APA template\n\n* [qapaja](https://github.com/crsh/qapaja/)\n\n* [apaquarto](https://github.com/wjschne/apaquarto)\n\n* [Hikmah Quarto templates](https://github.com/andrewheiss/hikmah-academic-quarto)\n\n\n# Extracting statistics\n\n## Extracting statistics\n\n![](../images/papaja_hex.png){.absolute width=\"15%\" top=\"-5%\" left=\"85%\"}\n\n`apa_print()`\n\n## Run a t-test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\nlibrary(tidyverse)\n(penguin_ttest <- t.test(formula = bill_length_mm ~ sex, data = penguins))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  bill_length_mm by sex\nt = -6.6725, df = 329.29, p-value = 1.066e-10\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -4.865676 -2.649908\nsample estimates:\nmean in group female   mean in group male \n            42.09697             45.85476 \n```\n\n\n:::\n:::\n\n\n\n\n## View structure of a t-test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(penguin_ttest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 10\n $ statistic  : Named num -6.67\n  ..- attr(*, \"names\")= chr \"t\"\n $ parameter  : Named num 329\n  ..- attr(*, \"names\")= chr \"df\"\n $ p.value    : num 1.07e-10\n $ conf.int   : num [1:2] -4.87 -2.65\n  ..- attr(*, \"conf.level\")= num 0.95\n $ estimate   : Named num [1:2] 42.1 45.9\n  ..- attr(*, \"names\")= chr [1:2] \"mean in group female\" \"mean in group male\"\n $ null.value : Named num 0\n  ..- attr(*, \"names\")= chr \"difference in means between group female and group male\"\n $ stderr     : num 0.563\n $ alternative: chr \"two.sided\"\n $ method     : chr \"Welch Two Sample t-test\"\n $ data.name  : chr \"bill_length_mm by sex\"\n - attr(*, \"class\")= chr \"htest\"\n```\n\n\n:::\n:::\n\n\n\n\n\n## Extract information from t-test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(papaja)\napa_print(penguin_ttest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$estimate\n[1] \"$\\\\Delta M = -3.76$, 95\\\\% CI $[-4.87, -2.65]$\"\n\n$statistic\n[1] \"$t(329.29) = -6.67$, $p < .001$\"\n\n$full_result\n[1] \"$\\\\Delta M = -3.76$, 95\\\\% CI $[-4.87, -2.65]$, $t(329.29) = -6.67$, $p < .001$\"\n\n$table\nA data.frame with 5 labelled columns:\n\n  estimate       conf.int statistic     df p.value\n1    -3.76 [-4.87, -2.65]     -6.67 329.29  < .001\n\nestimate : $\\\\Delta M$ \nconf.int : 95\\\\% CI \nstatistic: $t$ \ndf       : $\\\\mathit{df}$ \np.value  : $p$ \nattr(,\"class\")\n[1] \"apa_results\" \"list\"       \n```\n\n\n:::\n:::\n\n\n\n\n\n## Extract information from t-test\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\napa_print(penguin_ttest)$full_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"$\\\\Delta M = -3.76$, 95\\\\% CI $[-4.87, -2.65]$, $t(329.29) = -6.67$, $p < .001$\"\n```\n\n\n:::\n:::\n\n\n\n\n\n## Insert statistics as inline code\n\n<code>\nMale and female penguins differ in their bill length (&#96;r apa_print(penguin_ttest)$full_result&#96;).\n</code>\n\n::: {.fragment}\nMale and female penguins differ in their bill length ($\\Delta M = -3.76$, 95\\% CI $[-4.87, -2.65]$, $t(329.29) = -6.67$, $p < .001$).\n:::\n\n\n## `apa_print()` objects\n\n::: {style=\"font-size:90%\"}\n\n:::: {.columns}\n\n::: {.column width=50%}\n* Non-parametrics (`wilcox.test()`)\n* Correlations (`cor.test()`)\n* T-tests (`t.test()`)\n* ANOVA (`aov()`, `Anova()`, `afex_aov()`)\n* MANOVA (`manova()`)\n* Linear regressions (`lm()`)\n* Generalized linear models (`glm()`)\n:::\n\n::: {.column width=50%}\n* Mixed models (`lmer()`, `glmer()`)\n* Non-linear  models (`nlme()`)\n* Estimated marginal means (`emm()`)\n* Within-subjects confidence intervals (`wsci()`)\n* Bayes factors (from `{BayesFactor}` package)\n:::\n::::\n\n:::\n\n## Printing p-values\n\n`printp()`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprintp(0.23456)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \".235\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprintp(0.23456, add_equals = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"= .235\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprintp(0.000000000000001)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"< .001\"\n```\n\n\n:::\n:::\n\n\n\n\n\n## Printing other numbers\n\n`printnum()`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprintnum(0.5555555)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0.56\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprintnum(0.5555555, digits = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0.5556\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprintnum(0.5555555, gt1 = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \".56\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprintnum(0.00000000000001)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0.00\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprintnum(0.00000000000001, zero = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"< 0.01\"\n```\n\n\n:::\n:::\n\n\n\n\n\n## Examples of extracting statistics\n\n* [Rmd](https://osf.io/2xhzu)\n\n* [PDF](https://osf.io/pxmf6)\n\n\n# Before and after journal articles\n\n## Pre-registration templates\n\n[{prereg}](https://github.com/crsh/prereg)\n\n\n[{preregr}](https://preregr.opens.science/)\n\n\n## Revision letter template\n\n![](../images/papaja_hex.png){.absolute width=\"15%\" top=\"-5%\" left=\"85%\"}\n\n![](../images/revision-letter-template.png){fig-align=\"center\" width=\"55%\"}\n\n[Friends don't let friends copy-paste](https://frederikaust.com/papaja-workshop/slides/5_revision.html)\n\n\n# Dissertations\n\n## Dissertations in R Markdown\n\n![](../images/thesisdown_hex.png){.absolute width=\"15%\" top=\"-5%\" left=\"85%\"}\n\n![](../images/thesisdown-project.png){fig-align=\"center\" width=\"55%\"}\n\n\n\n## Let's code!\n\n[Journal articles](../code/40_publications.html){target=\"_blank\"} [[Rmd](../code/40_publications.Rmd){target=\"_blank\"}]\n",
    "supporting": [
      "40_publications_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}