---
title: 'Mutating columns'
author:
  - Jeff Stevens
date: '2023-02-15'
categories: 
  - "module 3"
  - "week 4"
  - across
  - case_when
  - columns
  - "conditional statements"
  - ifelse
  - mutate
  - rowwise
description: "Change and create data in columns"
draft: true
---

We'll continue our data wrangling by cleaning up the columns of our data. We'll use the [{dplyr}](https://dplyr.tidyverse.org) `mutate()` functions to change and create column data.

## Learning objectives

* Change existing column values
* Create new columns
* Move new columns when creating them
* Apply functions across columns

## Pre-meeting

To prepare for this class meeting, please do the following:

* Read [R4DS2 4.3.1](https://r4ds.hadley.nz/data-transform.html#sec-mutate){target='_blank'}

## Class meeting

* Changing columns
* Conditional changes
* Multiple changes
* Creating columns
* Moving columns when creating
* Removing old columns
* Applying functions to multiple columns
* Changing multiple columns
* [Slides](../../slides/11_mutating.qmd){target="_blank"} and [Code](../../code/11_mutating.html){target="_blank"}


## Homework after the class meeting
### Wrap up this lesson

* Complete the [exercises](https://its-ianr-shiny.unl.edu/users/jstevens5/dpavir2025/11_mutating/){target='_blank'}

### For next class meeting

* Read [R4DS2 5](https://r4ds.hadley.nz/workflow-pipes.html){target='_blank'}
